import type { ReportedArticle } from "@/lib/reported-articles";

const commonsImage = (file: string) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}?width=1600`;

export const researchedDeskArticles: Record<string, ReportedArticle> = {
  "02f75aca84321697156f": {
    kind: "reported-analysis",
    format: "news",
    title: "The Fox Theatre turned its rooftop terrace into an all-weather club",
    description: "The new Arcade Lounge encloses part of the Fox Theatre’s Marquee Club rooftop, adding year-round premium space above Peachtree Street.",
    label: "Inside the Fox",
    lede: "One of the Fox Theatre’s best views no longer depends on cooperative Atlanta weather. The theater has enclosed its third-floor terrace and reopened it as the Arcade Lounge, extending the members-only Marquee Club into a room that can operate through heat, rain and cold.",
    summaryLabel: "What changed",
    keyFacts: ["The Arcade Lounge replaces an open-air third-floor terrace.", "It expands the Marquee Club rather than creating a separate general-admission venue.", "Marquee Club access remains an add-on to a performance ticket."],
    sections: [
      { heading: "A rooftop becomes a room", paragraphs: ["Rough Draft Atlanta reported that the former terrace is now fully enclosed. Photographs from the project show a glass-walled lounge overlooking the Fox marquee and Peachtree Street, preserving the view while making the space useful beyond mild evenings.", "The change is practical, but it also nudges the Fox further into the premium-hospitality business. A historic theater that once sold almost entirely around the seat now has another product built around the hours before and after a show."] },
      { heading: "What a Marquee Club pass includes", paragraphs: ["The Fox describes the Marquee Club as a performance-night add-on with early entry, complimentary food, bars, private restrooms and rooftop access. A club pass does not include admission to the show, and post-show access can depend on demand.", "That distinction matters for anyone planning a visit: the Arcade Lounge is part of the club experience, not a new public rooftop bar. Availability is tied to individual performances and the theater’s premium memberships."] },
      { heading: "The larger bet", paragraphs: ["Enclosing the terrace gives the Fox more reliable capacity without altering the auditorium that defines the building. It is a small construction project compared with a theater renovation, but a meaningful one for how the venue earns revenue and manages crowds around sold-out shows."] },
    ],
    keywords: ["Fox Theatre Arcade Lounge", "Marquee Club Atlanta", "Fox Theatre rooftop", "Midtown Atlanta"],
    entities: ["Fox Theatre", "Marquee Club", "Midtown Atlanta"],
    image: { src: "https://i0.wp.com/roughdraftatlanta.com/wp-content/uploads/2026/08/1.Fox-Theatre-Arcade-Terrace_photo-credit-ALIVECOVERAGE.jpg?resize=1600%2C1067&ssl=1", alt: "The enclosed Arcade Lounge at Atlanta's Fox Theatre", credit: "ALIVE Coverage via Rough Draft Atlanta", creditUrl: "https://roughdraftatlanta.com/2026/08/16/fox-theatre-atlanta-opens-arcade-lounge-rooftop-bar/", label: "Source image", caption: "The Fox Theatre’s newly enclosed Arcade Lounge" },
    sources: [
      { name: "Rough Draft Atlanta", detail: "Reported the completed enclosure and photographed the new lounge.", url: "https://roughdraftatlanta.com/2026/08/16/fox-theatre-atlanta-opens-arcade-lounge-rooftop-bar/" },
      { name: "Fox Theatre", detail: "Official Marquee Club access, amenities and ticket terms.", url: "https://foxtheatre.evenue.net/events/CLUB" },
    ],
  },
  "e2b73db7ea6222a917b2": {
    kind: "reported-analysis",
    format: "feature",
    title: "DeKalb honors a repeat spelling-bee finalist and a longtime airport volunteer",
    description: "Sarv Dharavane and Larry Scheinpflug arrived at the DeKalb commission from different worlds, but both were recognized for unusually sustained local achievement.",
    label: "Two DeKalb stories",
    lede: "A national spelling stage and a county airport board do not often share a headline. They did at DeKalb County’s Aug. 11 commission meeting, where officials recognized student Sarv Dharavane and aviation volunteer Larry Scheinpflug.",
    summaryLabel: "Who was honored",
    keyFacts: ["Sarv Dharavane finished third nationally for the second consecutive year.", "He represented the Georgia Association of Educators and Peachtree Charter Middle School.", "Larry Scheinpflug has served in DeKalb aviation advisory work for years."],
    sections: [
      { heading: "Sarv’s third-place finish was no one-year surprise", paragraphs: ["Scripps lists Dharavane as speller No. 56 in the 2026 national competition. The Tucker student returned to the finals after placing third in 2025 and again finished third in 2026. The Georgia Association of Educators says he was a three-time state champion before the national event.", "Those results put the county recognition in perspective. This was not a ceremonial nod for simply reaching Washington; it marked a sustained run near the top of a competition that drew 247 spellers in 2026."] },
      { heading: "A different kind of long service", paragraphs: ["Commissioners also recognized Scheinpflug, whose name appears across years of DeKalb-Peachtree Airport advisory records. County documents show his work on the Airport Advisory Board, including discussion of operating rules, standards and community-facing aviation projects.", "Placed together, the two recognitions made for an unusually broad local portrait: a young competitor building a national record and a volunteer whose work accumulated mostly outside public view."] },
    ],
    keywords: ["Sarv Dharavane", "Scripps National Spelling Bee 2026", "Larry Scheinpflug", "DeKalb County"],
    entities: ["DeKalb County", "Sarv Dharavane", "Larry Scheinpflug", "Scripps National Spelling Bee"],
    image: { src: "https://d26o8czchimmmz.cloudfront.net/images/photos/spellers/2026/056.jpg", alt: "2026 National Spelling Bee finalist Sarv Dharavane", credit: "Scripps National Spelling Bee", creditUrl: "https://spellingbee.com/meet-the-spellers?speller_number=56", label: "Official image", caption: "Sarv Dharavane represented Georgia at the 2026 national bee" },
    sources: [
      { name: "Rough Draft Atlanta", detail: "Reported the Aug. 11 DeKalb County recognitions.", url: "https://roughdraftatlanta.com/2026/08/16/dekalb-commissions-spelling-bee-third/" },
      { name: "Scripps National Spelling Bee", detail: "Official 2026 participant profile and competition record for Dharavane.", url: "https://spellingbee.com/meet-the-spellers?speller_number=56" },
      { name: "Georgia Association of Educators", detail: "Confirmed Dharavane’s state titles and repeat national third-place finish.", url: "https://gae.org/about-gae/media-center/press-releases/georgias-spelling-champion-repeats-third-best-speller-nation" },
      { name: "DeKalb County", detail: "Airport Advisory Board records documenting Scheinpflug’s service.", url: "https://dekalbcountyga.gov/sites/default/files/2026-01/PDK%20AAB%208_14_23_Meeting%20Minutes%20FINAL_0.pdf" },
    ],
  },
  "f30475f47eb731195efe": {
    kind: "reported-analysis",
    format: "service",
    title: "Atlanta’s hot weekend came with an I-285 shutdown, too",
    description: "The Aug. 15 weekend paired mid-90s temperatures and a heat advisory with a full I-285 closure between Cascade Road and Martin Luther King Jr. Drive.",
    label: "Weekend archive",
    lede: "Atlanta had two reasons to rethink an outdoor or cross-town trip on Saturday, Aug. 15: oppressive heat and a full interstate closure on the southwest side of the Perimeter.",
    summaryLabel: "The weekend conditions",
    keyFacts: ["A heat advisory remained in effect through 8 p.m. Aug. 15.", "Temperatures were forecast in the mid-90s.", "The closed I-285 lanes were scheduled to reopen at 5 a.m. Monday."],
    sections: [
      { heading: "Heat changed the safest time to be outside", paragraphs: ["The National Weather Service’s Atlanta office uses a forecast heat index of at least 105 degrees—or an air temperature of at least 103—as its Heat Advisory threshold. Its guidance emphasizes hydration, lighter clothing and moving strenuous activity away from the hottest part of the afternoon.", "This page records the conditions reported for Aug. 15; it is not a live warning. Readers making plans should use the current NWS Atlanta forecast rather than an archived article."] },
      { heading: "The road closure concentrated the inconvenience", paragraphs: ["At the same time, all lanes of I-285 were closed between Cascade Road and Martin Luther King Jr. Drive for scheduled work. That pushed traffic toward local streets and alternative interstate routes through a part of west Atlanta already coping with major interchange construction.", "Either event would have complicated a weekend trip. Together they made timing—and checking the route before leaving—more important than usual."] },
    ],
    keywords: ["Atlanta heat August 15 2026", "I-285 closure", "Cascade Road", "Atlanta weekend traffic"],
    entities: ["National Weather Service Atlanta", "Georgia Department of Transportation", "I-285"],
    image: { src: "https://www.weather.gov/images/ffc/DSS%20web%20page/FFC%20Banner%20(Heat%20Page).png", alt: "National Weather Service Atlanta heat information banner", credit: "National Weather Service Atlanta", creditUrl: "https://www.weather.gov/ffc/heat", label: "Official image", caption: "Archived heat coverage; check the NWS for current conditions", license: "U.S. government work" },
    sources: [
      { name: "Rough Draft Atlanta", detail: "Contemporaneous Aug. 15 weather and closure briefing.", url: "https://roughdraftatlanta.com/2026/08/15/%f0%9f%a5%b5-heat-wave-continues/" },
      { name: "National Weather Service Atlanta", detail: "Official heat-product thresholds and safety guidance.", url: "https://www.weather.gov/ffc/heat" },
      { name: "FOX 5 Atlanta", detail: "Reported GDOT’s full southwest Fulton closure and expected delays.", url: "https://www.fox5atlanta.com/news/i-285-closure-what-drivers-need-know-about-southwest-fulton-shutdown" },
    ],
  },
  "7fc6191bac887aec8cfe": {
    kind: "reported-analysis",
    format: "preview",
    title: "Summer Shade returns to Grant Park with two free days of music, art and food",
    description: "The 2026 Summer Shade Festival runs Aug. 22–23 inside Grant Park, with more than 140 artists and makers, two music stages and family programming.",
    label: "Plan your weekend",
    lede: "Grant Park’s end-of-summer ritual is back for its 24th year. Summer Shade will spread across Atlanta’s oldest public park on Aug. 22 and 23 with live music, artist booths, food vendors and programming built for an all-day visit.",
    summaryLabel: "Before you go",
    keyFacts: ["Saturday, Aug. 22 and Sunday, Aug. 23 in Grant Park.", "Admission is free.", "Festival proceeds support the Grant Park Conservancy."],
    sections: [
      { heading: "What is on the grounds", paragraphs: ["Organizers are programming music on the Main Stage and Gazebo alongside more than 140 artists and makers, vintage sellers, local food and family activities. The mix is intentionally broad: this is as much neighborhood gathering as ticketed-style music festival, without the ticket.", "The City of Atlanta lists the event inside Grant Park at 759 Boulevard SE. Its calendar gives operating hours of 10 a.m. to 10 p.m. Saturday and 10 a.m. to 6 p.m. Sunday; visitors should confirm final times with the organizer before leaving."] },
      { heading: "The park is also the beneficiary", paragraphs: ["Summer Shade is organized by and benefits the Grant Park Conservancy, the nonprofit responsible for restoration, maintenance and advocacy in the historic park. Spending at the festival therefore supports more than a weekend lineup.", "Large events make parking around Grant Park scarce quickly. The most useful plan is to arrive early, expect walking and check the festival’s transportation guidance and weather updates on the day of the event."] },
    ],
    keywords: ["Summer Shade Festival 2026", "Grant Park events", "Atlanta events August 2026", "free Atlanta festival"],
    entities: ["Grant Park Conservancy", "Summer Shade Festival", "Grant Park"],
    image: { src: "https://summershadefestival.org/wp-content/uploads/2026/06/August-22-23-2026-1-1024x683.png", alt: "Official 2026 Summer Shade Festival artwork", credit: "Grant Park Conservancy", creditUrl: "https://summershadefestival.org/", label: "Official image", caption: "The 2026 Summer Shade Festival runs Aug. 22–23" },
    sources: [
      { name: "Summer Shade Festival", detail: "Official dates, admission information and festival purpose.", url: "https://summershadefestival.org/" },
      { name: "City of Atlanta", detail: "Official city calendar listing with location and scheduled hours.", url: "https://www.atlantaga.gov/Home/Components/Calendar/Event/25253/660?npage=242&sortd=desc&sortn=EName&toggle=all" },
      { name: "Rough Draft Atlanta", detail: "Reported the 2026 music, maker and food lineup.", url: "https://roughdraftatlanta.com/2026/08/15/summer-shade-festival-grant-park/" },
    ],
  },
  "1ad1b99ddd21f51d8343": {
    kind: "reported-analysis",
    format: "news",
    title: "The Hawks’ summer court tour reached 1,600 kids across metro Atlanta",
    description: "The Atlanta Hawks Basketball Academy says its eight-week Community Court Tour delivered free clinics and wellness activities in 17 neighborhoods.",
    label: "Beyond game night",
    lede: "The Atlanta Hawks spent part of the offseason far from the arena floor. Their Basketball Academy’s 2026 Community Court Tour brought free clinics to parks and recreation centers across metro Atlanta, reaching more than 1,600 children over eight weeks.",
    summaryLabel: "The reach",
    keyFacts: ["More than 1,600 participants ages 5 to 16.", "Seventeen neighborhoods across five metro counties.", "The program is now in its sixth year."],
    sections: [
      { heading: "A regional program, not a one-day clinic", paragraphs: ["The tour moved through Cobb, DeKalb, Douglas, Fulton and Gwinnett counties. Hawks youth-development coaches and former players led basketball instruction, while the program paired court time with wellness activities.", "That geography matters. A downtown arena can feel remote to a child in an outer-county recreation program; bringing coaches and alumni to existing community courts reverses the trip."] },
      { heading: "The durable measure is repeat access", paragraphs: ["Team community programs often arrive as a single event and a photograph. The Hawks describe this one as an eight-week circuit in its sixth year, giving it a longer record than a conventional promotional stop.", "The next useful measure is not social engagement but continuity: whether the same recreation centers receive follow-up programming, equipment and safe court access after the summer tour ends."] },
    ],
    keywords: ["Atlanta Hawks Community Court Tour", "Hawks Basketball Academy", "Atlanta youth basketball", "free basketball clinics"],
    entities: ["Atlanta Hawks", "Atlanta Hawks Basketball Academy", "Metro Atlanta"],
    image: { src: "https://i0.wp.com/roughdraftatlanta.com/wp-content/uploads/2026/08/Hawks-Wrap-2026-Community-Court-Tour-Positively-Impacting-More-Than-1600-Youth.jpg?resize=1600%2C950&ssl=1", alt: "Young athletes participating in the Atlanta Hawks Community Court Tour", credit: "Atlanta Hawks via Rough Draft Atlanta", creditUrl: "https://roughdraftatlanta.com/2026/08/15/atlanta-hawks-community-court-tour/", label: "Source image", caption: "The Hawks brought free clinics to 17 metro-area neighborhoods" },
    sources: [
      { name: "Rough Draft Atlanta", detail: "Reported the 2026 participation, duration and county reach.", url: "https://roughdraftatlanta.com/2026/08/15/atlanta-hawks-community-court-tour/" },
      { name: "Atlanta Hawks", detail: "First-party photographs and prior Community Court Tour documentation.", url: "https://www.nba.com/hawks/photos/atlanta-hawks-community-court-tour-presented-by-quiktrip" },
      { name: "Atlanta Hawks Community Impact Report", detail: "Team report documenting the program’s community-development framework.", url: "https://cdn.atlhawksdigital.com/files/2425_HWK_MK_CSR_ImpactReport.pdf" },
    ],
  },
  "ef1eba9dded0a816c69d": {
    kind: "reported-analysis",
    format: "feature",
    title: "At the Atlanta Quilt Festival, music and history are stitched into the record",
    description: "The 18th Atlanta Quilt Festival brings more than 150 works to South Fulton, including a 50-quilt exhibition about music and social change.",
    label: "On view",
    lede: "A protest song can carry history through sound. At the Atlanta Quilt Festival, artists are asking what happens when that history is carried in fabric instead.",
    summaryLabel: "The exhibition",
    keyFacts: ["The festival runs through Sept. 5 at Southwest Arts Center.", "More than 150 quilts are on display.", "Music Moves Movements contains 50 original works."],
    sections: [
      { heading: "A theme large enough for more than one gallery", paragraphs: ["The non-juried Music Moves Movements exhibition follows music through political movements, Black history, enslavement, resistance and empowerment. SaportaReport counted 50 works in that section and more than 150 across the festival.", "Quilting is the medium, not a limit on the subject. The show moves between portraiture, text, pattern and archival memory, allowing artists to build arguments as well as objects."] },
      { heading: "The festival makes room for masters and beginners", paragraphs: ["The Atlanta Quilt Festival says its mission is twofold: preserve and promote African American quilting while creating an entry point for new makers. Its annual program combines a juried exhibition of more than 100 quilts with classes, lectures, trunk shows and less formal exhibits.", "That mix explains the festival’s staying power into an 18th year. Visitors can encounter finished work, but the schedule also treats quilting as knowledge meant to be passed along."] },
      { heading: "How to visit", paragraphs: ["The festival is at Southwest Arts Center, 915 New Hope Road in South Fulton. The organizer lists viewing from Aug. 1 through Sept. 5, generally Monday through Saturday, with individual classes and receptions on their own schedules. Some programs are free and others require registration or a ticket."] },
    ],
    keywords: ["Atlanta Quilt Festival 2026", "Music Moves Movements", "Southwest Arts Center", "African American quilting"],
    entities: ["Atlanta Quilt Festival", "Southwest Arts Center", "City of South Fulton"],
    image: { src: "https://static.wixstatic.com/media/e0f3c1_49c1e1f34c764d5fbf5ac2d1eabf1ea8%7Emv2.jpg/v1/fit/w_1600,h_900,al_c/e0f3c1_49c1e1f34c764d5fbf5ac2d1eabf1ea8%7Emv2.jpg", alt: "Quilts displayed by the Atlanta Quilt Festival", credit: "Atlanta Quilt Festival", creditUrl: "https://www.atlantaquiltfestival.com/", label: "Official image", caption: "The 18th Atlanta Quilt Festival continues through Sept. 5" },
    sources: [
      { name: "Atlanta Quilt Festival", detail: "Official dates, location, programming and organizational mission.", url: "https://www.atlantaquiltfestival.com/" },
      { name: "City of South Fulton", detail: "Municipal calendar confirming the festival schedule and venue.", url: "https://www.cityofsouthfultonga.gov/Calendar.aspx?EID=6493&calType=0&day=17&month=8&year=2026" },
      { name: "SaportaReport", detail: "On-site reporting on the exhibitions, artists and themes.", url: "https://saportareport.com/atlanta-quilt-festival-stitches-together-music-history-and-social-justice/columnists/adrianne-murchison/" },
    ],
  },
  "235ccc286834bd8d8cd5": {
    kind: "reported-analysis",
    format: "preview",
    title: "City Springs opens its ninth season with a three-hour ‘Les Misérables’",
    description: "The Sandy Springs company stages Les Misérables at Byers Theatre Sept. 11–27, with Tony winner Shuler Hensley directing.",
    label: "Stage preview",
    lede: "City Springs Theatre Company is not easing into season nine. It is opening with barricades, revolution and one of musical theater’s largest emotional canvases: ‘Les Misérables.’",
    summaryLabel: "Curtain details",
    keyFacts: ["Sept. 11–27 at Byers Theatre in Sandy Springs.", "The production runs approximately three hours.", "Shuler Hensley directs; the company recommends it for ages 13 and older."],
    sections: [
      { heading: "A demanding choice for opening night", paragraphs: ["The musical follows Jean Valjean from imprisonment through reinvention and pursuit in 19th-century France. Its size is part of the attraction—and the production challenge. The score requires a company capable of moving between intimate confession and full-ensemble spectacle without losing either.", "City Springs has placed Tony Award winner Shuler Hensley in the director’s chair. The company’s official material notes adult themes and violence, making this a different proposition from a family-oriented holiday title."] },
      { heading: "The rest of the season changes register", paragraphs: ["After ‘Les Misérables,’ the 2026–27 mainstage schedule continues with ‘Anastasia’ in December, ‘Dear Evan Hansen’ in March and ‘Grease’ beginning in late April. The sequence moves from epic historical drama to animated-film nostalgia, contemporary musical theater and a familiar crowd-pleaser.", "Performances are at Byers Theatre in the Sandy Springs Performing Arts Center. Ticket availability and individual performance times vary, so the company’s show page is the final source before making plans."] },
    ],
    keywords: ["Les Misérables Atlanta 2026", "City Springs Theatre Company", "Byers Theatre", "Shuler Hensley"],
    entities: ["City Springs Theatre Company", "Byers Theatre", "Shuler Hensley", "Sandy Springs"],
    image: { src: "https://www.cityspringstheatre.com/application/files/8817/8515/8381/Web_HeroWithPhoto_1300x600_LM_CosetteOnWhite.webp", alt: "Official artwork for City Springs Theatre Company's Les Misérables", credit: "City Springs Theatre Company", creditUrl: "https://www.cityspringstheatre.com/", label: "Official image", caption: "‘Les Misérables’ runs Sept. 11–27 at Byers Theatre" },
    sources: [
      { name: "City Springs Theatre Company", detail: "Official performance dates, venue, running time and ticket information.", url: "https://www.cityspringstheatre.com/" },
      { name: "City Springs 2026–27 season announcement", detail: "Official season lineup, production description and age guidance.", url: "https://www.cityspringstheatre.com/application/files/2217/7930/3569/CSTC_-_26_-_27_Season_subsciptions.pdf" },
      { name: "Rough Draft Atlanta", detail: "Local preview of the company’s ninth season.", url: "https://roughdraftatlanta.com/2026/08/14/city-springs-theatre-company-kicks-off-ninth-season-with-les-miserables/" },
    ],
  },
  "350e308a24e5a0326f80": {
    kind: "reported-analysis",
    format: "service",
    title: "Atlanta Falcons 2026 preseason schedule: dates, opponents and where they play",
    description: "The Falcons opened at home against Denver and finish the preseason with road games at Indianapolis and Miami.",
    label: "Falcons schedule",
    lede: "The Falcons get one preseason night at Mercedes-Benz Stadium before taking the rest of their August evaluation on the road.",
    summaryLabel: "All three games",
    keyFacts: ["Aug. 14: Denver at Atlanta, 7 p.m.", "Aug. 22: Atlanta at Indianapolis, 1 p.m.", "Aug. 28: Atlanta at Miami, 7 p.m."],
    sections: [
      { heading: "The schedule", paragraphs: ["Atlanta’s official schedule lists the opener against Denver at Mercedes-Benz Stadium, followed by a Saturday afternoon game at Indianapolis and a Friday night finale at Miami. The Colts game follows joint practices between the two teams.", "All three games are listed as local broadcasts by the league. FOX 5 Atlanta published local viewing information for the preseason; viewers should confirm the station and streaming availability near kickoff because distribution can vary by market."] },
      { heading: "What preseason is actually deciding", paragraphs: ["The results do not count in the regular-season standings, but the snaps do. Coaches use these games to settle roster depth, special-teams roles and the final places on the initial 53-player roster.", "For fans attending the lone home game, the practical effect is regular event-night traffic and transit demand around Mercedes-Benz Stadium. The two road dates shift the experience back to local television before Atlanta opens the regular season at Pittsburgh on Sept. 13."] },
    ],
    keywords: ["Atlanta Falcons preseason schedule 2026", "Falcons Broncos August 14", "Falcons Colts preseason", "Falcons Dolphins preseason"],
    entities: ["Atlanta Falcons", "Denver Broncos", "Indianapolis Colts", "Miami Dolphins", "Mercedes-Benz Stadium"],
    image: { src: commonsImage("Mercedes-Benz Stadium, December 2024.jpg"), alt: "Exterior of Mercedes-Benz Stadium in Atlanta", credit: "BullDawg2021 / Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_Stadium,_December_2024.jpg", label: "Licensed image", caption: "Atlanta plays one 2026 preseason game at Mercedes-Benz Stadium", license: "CC BY 4.0" },
    sources: [
      { name: "Atlanta Falcons", detail: "Official 2026 schedule and venue information.", url: "https://www.atlantafalcons.com/schedule/" },
      { name: "NFL", detail: "League schedule confirming all three preseason dates and times.", url: "https://www.nfl.com/schedules/2026/by-team/atlanta-falcons" },
      { name: "FOX 5 Atlanta", detail: "Local preseason viewing information.", url: "https://www.fox5atlanta.com/news/atlanta-falcons-preseason-2026-fox-local-schedule-how-watch" },
    ],
  },
  "697c18f6c4bd463bd665": {
    kind: "reported-analysis",
    format: "preview",
    title: "Eight emerging filmmakers bring ‘Resisting Narratives of Erasure’ to the Tara",
    description: "Visionary Justice StoryLab’s Aug. 20 showcase at the Tara Theatre closes a fellowship for young Southeastern women and nonbinary filmmakers.",
    label: "Film preview",
    lede: "The films arriving at the Tara Theatre on Aug. 20 began as a deliberate answer to absence: who is encouraged to direct, whose lives reach the screen and which Southern stories are treated as worth preserving.",
    summaryLabel: "The showcase",
    keyFacts: ["Aug. 20 at Atlanta’s Tara Theatre.", "Eight original short films are scheduled.", "The showcase concludes the 2026 Resisting Narratives of Erasure fellowship."],
    sections: [
      { heading: "A screening built from a fellowship", paragraphs: ["Visionary Justice StoryLab designed the program for early-career filmmakers ages 18 to 25 living in the Southeast. Its stated focus is women and nonbinary artists, particularly storytellers working with intersectional and QTBIPOC-centered narratives.", "Participants receive production funding, mentorship, professional development and a creative cohort. The Tara event is therefore more than a themed film night: it is the public finish line for work developed through the year."] },
      { heading: "Why the venue fits", paragraphs: ["The Tara has re-emerged as one of Atlanta’s most visible homes for independent and repertory film. Putting eight new regional shorts on that screen gives the filmmakers a theatrical premiere rather than treating the work as disposable online content.", "Event timing, ticket availability and accessibility details should be confirmed through the organizer. The StoryLab site also introduces the 2026 fellows and the broader series behind the showcase."] },
    ],
    keywords: ["Visionary Justice StoryLab 2026", "Tara Theatre Atlanta", "Resisting Narratives of Erasure", "Atlanta short films"],
    entities: ["Visionary Justice StoryLab", "Tara Theatre", "Atlanta film"],
    image: { src: "https://images.squarespace-cdn.com/content/v1/59cc88ba9f745669f143edcf/ebfc84af-2937-46c8-ab88-c18314d8e5db/2026+RNE+Poster+%287%29.png?format=1500w", alt: "Official poster for the 2026 Resisting Narratives of Erasure program", credit: "Visionary Justice StoryLab", creditUrl: "https://www.visionaryjusticestorylab.org/", label: "Official image", caption: "The fellowship’s eight short films screen Aug. 20" },
    sources: [
      { name: "Visionary Justice StoryLab", detail: "Official program, fellowship and filmmaker information.", url: "https://www.visionaryjusticestorylab.org/" },
      { name: "Resisting Narratives of Erasure", detail: "Official eligibility, support and premiere description for the 2026 fellowship.", url: "https://www.visionaryjusticestorylab.org/apply" },
      { name: "Rough Draft Atlanta", detail: "Reported the Tara Theatre date and eight-film showcase.", url: "https://roughdraftatlanta.com/2026/08/14/visionary-justice-storylab-to-celebrate-southeastern-filmmakers-with-screening-event-on-aug-20/" },
    ],
  },
  "22fbec87ba014f4cfa48": {
    kind: "reported-analysis",
    format: "service",
    title: "The southwest Atlanta I-285 closure: where it happened and why traffic spread",
    description: "GDOT’s full weekend shutdown between Cascade Road and Martin Luther King Jr. Drive closed a critical westside segment of the Perimeter.",
    label: "Road closure archive",
    lede: "A full interstate closure is different from a bad lane reduction: there is no route through it. On the Aug. 15 weekend, drivers approaching southwest Atlanta’s I-285 work zone had to leave the Perimeter entirely.",
    summaryLabel: "Closure record",
    keyFacts: ["All lanes closed between Cascade Road and Martin Luther King Jr. Drive.", "The shutdown affected a major southwest Fulton segment of I-285.", "Lanes were scheduled to reopen at 5 a.m. Monday."],
    sections: [
      { heading: "Why the effects extended beyond the interstate", paragraphs: ["FOX 5 Atlanta reported that GDOT closed the full segment for weekend construction. With through traffic removed, detours placed additional demand on I-20, Fulton Industrial Boulevard and local westside streets.", "The closure sat within the much larger I-285/I-20 West Interchange program. GDOT’s project material describes reconstruction intended to improve operations at one of the region’s busiest and most complicated highway connections."] },
      { heading: "This is an archive, not a live traffic alert", paragraphs: ["The closure window described here has passed. ATLSignal is keeping the page because the construction program will produce additional traffic changes, but drivers should use Georgia 511 or GDOT’s current project notices before traveling.", "The durable story is the construction sequence: large interchange work often moves through repeated weekend closures rather than one continuous shutdown. Each new phase needs a fresh notice with exact dates and boundaries."] },
    ],
    keywords: ["I-285 closure southwest Fulton", "I-285 I-20 West Interchange", "Cascade Road closure", "Atlanta traffic"],
    entities: ["Georgia Department of Transportation", "I-285", "I-20 West Interchange", "Southwest Fulton"],
    image: { src: commonsImage("Camp Creek at I-285 Aerial (50924270112).jpg"), alt: "Aerial view of I-285 at Camp Creek Parkway in southwest Fulton County", credit: "formulanone / Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Camp_Creek_at_I-285_Aerial_(50924270112).jpg", label: "Licensed image", caption: "I-285 at Camp Creek Parkway in southwest Fulton", license: "CC BY-SA 2.0" },
    sources: [
      { name: "FOX 5 Atlanta", detail: "Reported the closure boundary, timing and GDOT traffic warning.", url: "https://www.fox5atlanta.com/news/i-285-closure-what-drivers-need-know-about-southwest-fulton-shutdown" },
      { name: "Georgia DOT", detail: "Official June 2026 presentation for the I-285/I-20 West Interchange program.", url: "https://www.dot.ga.gov/systems/ProjectDocuments/0013918/June%202026%20Community%20Meeting%20Presentation.pdf" },
      { name: "Georgia 511", detail: "Current official traffic and closure information.", url: "https://511ga.org/" },
    ],
  },
  "c61cfffb32cfa4acc526": {
    kind: "reported-analysis",
    format: "service",
    title: "What a 109-degree heat index means in Atlanta",
    description: "An Atlanta-area advisory projected heat indices as high as 109 degrees. Here is how the National Weather Service defines that risk and what the number does—and does not—measure.",
    label: "Heat explained",
    lede: "The number that mattered in Atlanta’s heat advisory was not the thermometer reading. It was 109—the upper end of the projected heat index, where temperature and humidity combine into a much more punishing measure of how conditions affect the body.",
    summaryLabel: "The advisory",
    keyFacts: ["The advisory described heat-index values reaching 109 degrees.", "NWS Atlanta’s Heat Advisory threshold begins at a 105-degree heat index or 103-degree air temperature.", "Heat index is calculated for shaded, light-wind conditions; direct sun can make exposure feel hotter."],
    sections: [
      { heading: "Why humidity changes the danger", paragraphs: ["Sweat cools the body when it evaporates. High humidity slows that process, which is why a mid-90s air temperature can produce a heat index well above 100. The index is an impact measure, not another name for the forecast high.", "The National Weather Service says its published heat-index values assume shade and light wind. Full sunshine can add substantially to heat stress, especially for people working, exercising or waiting on exposed pavement."] },
      { heading: "The warning has an expiration date; the guidance does not", paragraphs: ["Rough Draft Atlanta reported that the advisory covered most of Georgia from noon to 8 p.m. and projected values up to 109. That specific warning window is now historical. It should not be used to describe today’s conditions.", "During any new advisory, NWS guidance is straightforward: reduce strenuous afternoon activity, drink fluids, use air conditioning when possible and check on people without reliable cooling. Symptoms of heat exhaustion or heat stroke require prompt action."] },
      { heading: "Check the live source", paragraphs: ["Weather pages age faster than almost any other local article. The NWS Atlanta forecast and active-alert pages—not an archived headline—should decide present-day plans."] },
    ],
    keywords: ["Atlanta heat index 109", "Georgia heat advisory", "heat index explained", "NWS Atlanta heat safety"],
    entities: ["National Weather Service Atlanta", "Atlanta", "Georgia"],
    image: { src: "https://www.weather.gov/images/ffc/Heat-Index-refreshed.png", alt: "National Weather Service heat index chart", credit: "National Weather Service Atlanta", creditUrl: "https://www.weather.gov/ffc/heat", label: "Official image", caption: "The heat index combines air temperature and relative humidity", license: "U.S. government work" },
    sources: [
      { name: "National Weather Service Atlanta", detail: "Official heat thresholds, measurement explanation and safety guidance.", url: "https://www.weather.gov/ffc/heat" },
      { name: "Rough Draft Atlanta", detail: "Contemporaneous report of the advisory window and projected 109-degree heat index.", url: "https://roughdraftatlanta.com/2026/08/14/georgia-heat-warning-today/" },
    ],
  },
  "97b180015bc3b56bb362": {
    kind: "reported-analysis",
    format: "analysis",
    title: "A 375-unit proposal would redraw a low-rise stretch of Ponce",
    description: "Selig Enterprises’ Virginia-Highland plan combines 375 apartments and ground-floor commercial space on 1.75 acres near Hotel Clermont.",
    label: "Development watch",
    lede: "Ponce de Leon Avenue has absorbed waves of redevelopment without losing all of its low-rise, slightly unruly commercial character. Selig Enterprises’ latest proposal tests how much of that character can survive when 375 apartments arrive on less than two acres.",
    summaryLabel: "The proposal",
    keyFacts: ["Up to 375 multifamily units on approximately 1.75 acres.", "About 10,000 square feet of ground-floor commercial space.", "The proposal advanced through Atlanta’s Zoning Review Board."],
    sections: [
      { heading: "More housing, on a very visible block", paragraphs: ["The site sits on the Virginia-Highland side of Ponce near Hotel Clermont and the Eastside Trail corridor. Rough Draft Atlanta reported that the Zoning Review Board approved the proposal, moving it forward in the city process.", "Axios previously reported that the plan would replace several aging commercial buildings while leaving The Local property outside the development boundary. That detail matters because much of the neighborhood response has centered on whether new density requires erasing the establishments that gave the corridor its identity."] },
      { heading: "The numbers describe density, not affordability", paragraphs: ["Three hundred seventy-five units would add meaningful housing supply in a walkable intown location. The public descriptions reviewed by ATLSignal do not, however, establish an affordable-housing commitment. More homes and more affordable homes are related policy goals, but they are not interchangeable.", "The ground floor is expected to return commercial activity to Ponce. The quality of that frontage—number of storefronts, sidewalk design, loading and parking access—will determine whether the project strengthens the street or simply places a large residential building beside it."] },
      { heading: "Approval is not construction", paragraphs: ["A zoning recommendation is an important milestone, not a groundbreaking. Final city action, revised plans, permits and financing remain the records that would turn the proposal into a buildable project."] },
    ],
    keywords: ["Selig Ponce de Leon development", "375 apartments Virginia Highland", "Ponce de Leon rezoning", "Atlanta housing development"],
    entities: ["Selig Enterprises", "Virginia-Highland", "Ponce de Leon Avenue", "City of Atlanta"],
    image: { src: "https://i0.wp.com/roughdraftatlanta.com/wp-content/uploads/2026/08/Selig-Ponce-development.png?resize=1600%2C1151&ssl=1", alt: "Rendering of Selig Enterprises' proposed Ponce de Leon Avenue development", credit: "Selig Enterprises via Rough Draft Atlanta", creditUrl: "https://roughdraftatlanta.com/2026/08/13/selig-redevelopment-ponce-de-leon/", label: "Source image", caption: "Rendering of the proposed 375-unit Ponce development" },
    sources: [
      { name: "Rough Draft Atlanta", detail: "Reported the Zoning Review Board action, site size and current proposal.", url: "https://roughdraftatlanta.com/2026/08/13/selig-redevelopment-ponce-de-leon/" },
      { name: "Axios Atlanta", detail: "Earlier reporting on the 375 units, commercial space and properties within the proposed redevelopment.", url: "https://www.axios.com/local/atlanta/2026/07/28/selig-enterprises-ponce-corridor-rezoning-375-unit-development-virginia-highland-atlanta" },
      { name: "Selig Enterprises", detail: "First-party description of the company’s development and operating portfolio.", url: "https://seligenterprises.com/development-initiatives/" },
    ],
    showUpdateHistory: true,
  },
  "79f8e0f643ac8506808c": {
    kind: "reported-analysis",
    format: "preview",
    title: "Sargent opens on the Beltline with oysters, books and room to linger",
    description: "The Lucian team’s 150-seat Old Fourth Ward restaurant opens Aug. 18 with an American brasserie menu, cocktails and a dedicated bookshop.",
    label: "Opening Aug. 18",
    lede: "Lucian Books & Wine became a Buckhead favorite by making dinner feel like time spent inside someone’s very good taste. Sargent, opening Aug. 18 in Old Fourth Ward, keeps the books and wine but gives the idea more space, more cocktails and a front door near the Beltline.",
    summaryLabel: "What to expect",
    keyFacts: ["Sargent opens Aug. 18 at 405 N. Angier Ave. NE.", "The restaurant seats about 150 and covers roughly 6,000 square feet.", "The concept combines an American brasserie, full bar and dedicated book-and-magazine shop."],
    sections: [
      { heading: "Lucian’s next act is not meant to be a duplicate", paragraphs: ["Owners Katie Barringer, Jordan Smelt and Mickey Mixson have described Sargent as a more energetic, everyday restaurant than Lucian. Chef Jason Paolini’s menu leans toward American brasserie cooking, with wood-fired dishes, oysters and composed classics rather than a copy of the Buckhead menu.", "Smelt’s beverage program gives cocktails a larger role and pulls more wine from American and other New World producers. Barringer’s retail area expands the original restaurant’s book selection into a distinct shop carrying art, design, food, music and culture titles."] },
      { heading: "The Beltline location changes the rhythm", paragraphs: ["Sargent sits at 405 N. Angier Ave. beside 3 Parks Wine Shop in the New City Properties development that includes Forth Hotel. A covered patio connects the restaurant to a part of the Eastside Trail where hotels, offices and destination dining increasingly overlap.", "At approximately 150 seats, the room is nearly three times Lucian’s size. That scale can make Sargent easier to enter and harder to keep intimate—the central tension in translating a beloved small restaurant into a larger second act."] },
      { heading: "The practical details", paragraphs: ["Atlanta Magazine reported the Aug. 18 opening date. Reservations, current hours and menu availability should be confirmed directly with the restaurant as opening-week operations settle."] },
    ],
    keywords: ["Sargent Atlanta restaurant", "Sargent Beltline opening", "Lucian Books and Wine", "Old Fourth Ward restaurants"],
    entities: ["Sargent", "Lucian Books & Wine", "Katie Barringer", "Jordan Smelt", "Jason Paolini", "Old Fourth Ward"],
    image: { src: "https://cdn2.atlantamagazine.com/wp-content/uploads/sites/4/2026/08/07.17.26_sargent_final_0064.jpg", alt: "Oysters served at Sargent in Atlanta's Old Fourth Ward", credit: "Andrew Thomas Lee / Atlanta Magazine", creditUrl: "https://www.atlantamagazine.com/dining-news/opening-aug-18-the-lucian-teams-next-act-sargent-is-built-for-the-beltline/", label: "Source image", caption: "Sargent brings an American brasserie menu to the Eastside Beltline" },
    sources: [
      { name: "Atlanta Magazine", detail: "Opening-week reporting, menu details and Aug. 18 opening date.", url: "https://www.atlantamagazine.com/dining-news/opening-aug-18-the-lucian-teams-next-act-sargent-is-built-for-the-beltline/" },
      { name: "Atlanta Journal-Constitution", detail: "Original reporting on the owners, address, design, capacity and concept.", url: "https://www.ajc.com/food-and-dining/atlanta-restaurant-sargent-to-open-on-eastside-beltline/ZBICIEERMNHENEZTA62RRNREFQ/" },
      { name: "Rough Draft Atlanta", detail: "Earlier interview with the owners about the restaurant’s identity and Beltline location.", url: "https://roughdraftatlanta.com/2025/02/12/lucian-owners-opening-sargent-new-city-old-fourth-ward-atlanta/" },
    ],
  },
};
